plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.143'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

neoForge {
    version = neo_version

    runs {
        client {
            client()
            systemProperty 'neoforge.logging.markers', 'REGISTRIES'
            systemProperty 'neoforge.logging.console.level', 'debug'
        }
        server {
            server()
            systemProperty 'neoforge.logging.markers', 'REGISTRIES'
            systemProperty 'neoforge.logging.console.level', 'debug'
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : "Who Goes There?",
                "Specification-Vendor"    : "Tendo Alice",
                "Specification-Version"   : "1",
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.version,
                "Implementation-Vendor"   : "Tendo Alice",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
